IMPORT LIBRARIES

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

IMPORT DATASET

In [82]:
data = pd.read_csv("Data.csv")

In [83]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [84]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [85]:
#Encoding the feature columns
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x)) # since this doesn't return a np array, we need to typeacast it
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [86]:
le = LabelEncoder()
y =le.fit_transform(y)

In [87]:
# Splitting the data into Training Set and TEst Set
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x, y, test_size=0.2)

In [ ]:
# Feature Scaling 
ss = StandardScaler()
Xtrain[:,3:] = ss.fit_transform(Xtrain[:,3:])

In [90]:
Xtest[:,3:] = ss.transform(Xtest[:,3:])